-- ============================================================
-- Teleport.me — Seed Data
-- 55 cities with scores
-- ============================================================

BEGIN;

-- Cities
INSERT INTO cities (id, name, full_name, country, continent, latitude, longitude, population, teleport_city_score, summary, image_url) VALUES
  ('san-francisco', 'San Francisco', 'San Francisco, California, United States', 'United States', 'North America', 37.7749, -122.4194, 874961, 65.59, 'A global hub for technology and innovation, San Francisco offers world-class startups and venture capital but struggles with extremely high housing costs.', 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=800&q=80'),
  ('new-york', 'New York', 'New York City, New York, United States', 'United States', 'North America', 40.7128, -74.006, 8336817, 66.47, 'The cultural and financial capital of the world, New York City offers unmatched arts, dining, and economic opportunity alongside notoriously high living costs.', 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80'),
  ('austin', 'Austin', 'Austin, Texas, United States', 'United States', 'North America', 30.2672, -97.7431, 978908, 64.12, 'A vibrant tech hub with a thriving music scene, Austin offers strong startup culture and moderate costs compared to coastal cities.', 'https://images.unsplash.com/photo-1531218150217-54595bc2b934?auto=format&fit=crop&w=800&q=80'),
  ('seattle', 'Seattle', 'Seattle, Washington, United States', 'United States', 'North America', 47.6062, -122.3321, 737015, 64.71, 'Home to major tech giants, Seattle combines a strong innovation economy with stunning Pacific Northwest scenery and outdoor recreation.', 'https://images.unsplash.com/photo-1502175353174-a7a70e73b4c3?auto=format&fit=crop&w=800&q=80'),
  ('portland', 'Portland', 'Portland, Oregon, United States', 'United States', 'North America', 45.5152, -122.6784, 652503, 63.53, 'Known for its quirky culture and eco-consciousness, Portland offers excellent cycling infrastructure, a vibrant food scene, and easy access to nature.', 'https://images.unsplash.com/photo-1507245338956-23ef52481479?auto=format&fit=crop&w=800&q=80'),
  ('denver', 'Denver', 'Denver, Colorado, United States', 'United States', 'North America', 39.7392, -104.9903, 715522, 63.53, 'The Mile High City offers unmatched access to Rocky Mountain outdoor recreation alongside a growing tech sector and craft beer culture.', 'https://images.unsplash.com/photo-1546156929-a4c0ac411f47?auto=format&fit=crop&w=800&q=80'),
  ('miami', 'Miami', 'Miami, Florida, United States', 'United States', 'North America', 25.7617, -80.1918, 467963, 60.59, 'A tropical gateway to Latin America, Miami offers warm weather year-round, a vibrant nightlife, and a growing tech and finance sector.', 'https://images.unsplash.com/photo-1506966953602-c20cc11f75e3?auto=format&fit=crop&w=800&q=80'),
  ('nashville', 'Nashville', 'Nashville, Tennessee, United States', 'United States', 'North America', 36.1627, -86.7816, 689447, 59.41, 'Music City is booming with a growing economy, affordable living by major city standards, and a legendary country music and food scene.', 'https://images.unsplash.com/photo-1545419913-775e00e202ec?auto=format&fit=crop&w=800&q=80'),
  ('charleston', 'Charleston', 'Charleston, South Carolina, United States', 'United States', 'North America', 32.7765, -79.9311, 150227, 57.06, 'A charming Southern city known for its historic architecture, award-winning cuisine, and beautiful coastal scenery.', 'https://images.unsplash.com/photo-1569025743873-56e7e5e89e4a?auto=format&fit=crop&w=800&q=80'),
  ('chicago', 'Chicago', 'Chicago, Illinois, United States', 'United States', 'North America', 41.8781, -87.6298, 2693976, 65.29, 'The Windy City boasts world-class architecture, a diverse food scene, and a strong economy anchored by finance, manufacturing, and technology.', 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f?auto=format&fit=crop&w=800&q=80'),
  ('los-angeles', 'Los Angeles', 'Los Angeles, California, United States', 'United States', 'North America', 34.0522, -118.2437, 3979576, 60.59, 'The entertainment capital of the world, Los Angeles offers year-round sunshine, cultural diversity, and a sprawling creative economy.', 'https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?auto=format&fit=crop&w=800&q=80'),
  ('boston', 'Boston', 'Boston, Massachusetts, United States', 'United States', 'North America', 42.3601, -71.0589, 692600, 66.47, 'A world leader in education and healthcare, Boston combines prestigious universities and cutting-edge biotech with rich colonial history.', 'https://images.unsplash.com/photo-1501979376754-2ff867a4f659?auto=format&fit=crop&w=800&q=80'),
  ('toronto', 'Toronto', 'Toronto, Ontario, Canada', 'Canada', 'North America', 43.6532, -79.3832, 2794356, 65.88, 'Canada''s largest city is one of the most multicultural places on Earth, with a strong financial sector and excellent public healthcare.', 'https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=800&q=80'),
  ('vancouver', 'Vancouver', 'Vancouver, British Columbia, Canada', 'Canada', 'North America', 49.2827, -123.1207, 631486, 63.53, 'Nestled between mountains and ocean, Vancouver is one of the world''s most scenic cities, offering incredible natural beauty alongside a tolerant, multicultural society.', 'https://images.unsplash.com/photo-1559511260-66a68e7e2e09?auto=format&fit=crop&w=800&q=80'),
  ('montreal', 'Montreal', 'Montreal, Quebec, Canada', 'Canada', 'North America', 45.5017, -73.5673, 1762949, 66.47, 'A bilingual cultural powerhouse, Montreal combines European charm with North American energy, offering world-class festivals, affordable living, and excellent cuisine.', 'https://images.unsplash.com/photo-1519178614-68673b201f36?auto=format&fit=crop&w=800&q=80'),
  ('mexico-city', 'Mexico City', 'Mexico City, Mexico', 'Mexico', 'North America', 19.4326, -99.1332, 9209944, 58.24, 'One of the world''s largest metropolitan areas, Mexico City offers rich pre-Columbian and colonial history, incredible food, and an increasingly vibrant startup scene.', 'https://images.unsplash.com/photo-1518659526054-190340b32735?auto=format&fit=crop&w=800&q=80'),
  ('lisbon', 'Lisbon', 'Lisbon, Portugal', 'Portugal', 'Europe', 38.7223, -9.1393, 544851, 64.71, 'A sun-drenched European capital with a booming tech scene, Lisbon attracts digital nomads and entrepreneurs with its affordable living, rich history, and warm climate.', 'https://images.unsplash.com/photo-1536663815808-535e2280d2c2?auto=format&fit=crop&w=800&q=80'),
  ('london', 'London', 'London, United Kingdom', 'United Kingdom', 'Europe', 51.5074, -0.1278, 8982000, 67.06, 'A global financial and cultural capital, London offers unparalleled history, world-class museums, and exceptional international connectivity.', 'https://images.unsplash.com/photo-1486299267070-83823f5448dd?auto=format&fit=crop&w=800&q=80'),
  ('berlin', 'Berlin', 'Berlin, Germany', 'Germany', 'Europe', 52.52, 13.405, 3644826, 69.41, 'Europe''s creative capital, Berlin offers an unmatched arts and nightlife scene, affordable rent by Western European standards, and a thriving startup ecosystem.', 'https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&w=800&q=80'),
  ('barcelona', 'Barcelona', 'Barcelona, Spain', 'Spain', 'Europe', 41.3874, 2.1686, 1620343, 65.88, 'A Mediterranean jewel blending Gaudi''s architecture with beach culture, Barcelona offers a superb quality of life with warm weather and vibrant nightlife.', 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=800&q=80'),
  ('amsterdam', 'Amsterdam', 'Amsterdam, Netherlands', 'Netherlands', 'Europe', 52.3676, 4.9041, 872680, 68.82, 'Famous for its canals and cycling culture, Amsterdam is one of Europe''s most tolerant and well-connected cities with a strong tech and creative economy.', 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=800&q=80'),
  ('paris', 'Paris', 'Paris, France', 'France', 'Europe', 48.8566, 2.3522, 2161000, 66.47, 'The City of Light remains the world''s cultural benchmark, offering unmatched art, cuisine, and fashion alongside a growing startup ecosystem.', 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80'),
  ('prague', 'Prague', 'Prague, Czech Republic', 'Czech Republic', 'Europe', 50.0755, 14.4378, 1309000, 63.53, 'A fairy-tale Central European capital, Prague offers stunning Gothic and Baroque architecture, affordable living, and a growing technology sector.', 'https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=800&q=80'),
  ('copenhagen', 'Copenhagen', 'Copenhagen, Denmark', 'Denmark', 'Europe', 55.6761, 12.5683, 794128, 66.47, 'A Scandinavian design capital that consistently ranks among the happiest cities, Copenhagen offers excellent cycling infrastructure, great healthcare, and a high quality of life.', 'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?auto=format&fit=crop&w=800&q=80'),
  ('stockholm', 'Stockholm', 'Stockholm, Sweden', 'Sweden', 'Europe', 59.3293, 18.0686, 975904, 67.06, 'Built on 14 islands, Stockholm is a global leader in sustainability, innovation, and quality of life, producing more unicorn startups per capita than almost any other city.', 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=800&q=80'),
  ('dublin', 'Dublin', 'Dublin, Ireland', 'Ireland', 'Europe', 53.3498, -6.2603, 544107, 63.53, 'Ireland''s vibrant capital is a European tech hub, hosting the headquarters of many global companies, with a lively pub culture and friendly locals.', 'https://images.unsplash.com/photo-1549918864-48ac978761a4?auto=format&fit=crop&w=800&q=80'),
  ('tallinn', 'Tallinn', 'Tallinn, Estonia', 'Estonia', 'Europe', 59.437, 24.7536, 437619, 67.65, 'The world''s most digitally advanced capital, Tallinn pioneered e-residency and digital government, making it a magnet for tech entrepreneurs and digital nomads.', 'https://images.unsplash.com/photo-1565008576549-57569a49371d?auto=format&fit=crop&w=800&q=80'),
  ('zurich', 'Zurich', 'Zurich, Switzerland', 'Switzerland', 'Europe', 47.3769, 8.5417, 421878, 67.65, 'Switzerland''s financial powerhouse offers exceptional safety, pristine Alpine scenery, and world-class healthcare, though at some of the highest living costs anywhere.', 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?auto=format&fit=crop&w=800&q=80'),
  ('vienna', 'Vienna', 'Vienna, Austria', 'Austria', 'Europe', 48.2082, 16.3738, 1911728, 70.59, 'Repeatedly ranked the world''s most livable city, Vienna offers imperial architecture, legendary classical music, excellent public transport, and superb healthcare.', 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?auto=format&fit=crop&w=800&q=80'),
  ('munich', 'Munich', 'Munich, Germany', 'Germany', 'Europe', 48.1351, 11.582, 1471508, 67.06, 'Bavaria''s capital combines German engineering excellence with Alpine proximity, offering Oktoberfest traditions, a strong automotive economy, and high quality of life.', 'https://images.unsplash.com/photo-1595867818082-083862f3d630?auto=format&fit=crop&w=800&q=80'),
  ('tokyo', 'Tokyo', 'Tokyo, Japan', 'Japan', 'Asia', 35.6762, 139.6503, 13960000, 70.59, 'The world''s largest metropolitan area seamlessly blends ultra-modern technology with ancient temples, offering incredible safety, cuisine, and public transport.', 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80'),
  ('singapore', 'Singapore', 'Singapore', 'Singapore', 'Asia', 1.3521, 103.8198, 5850342, 70.0, 'A gleaming city-state at the crossroads of Asia, Singapore offers extraordinary safety, a powerhouse economy, and world-class infrastructure in a tropical setting.', 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80'),
  ('bangkok', 'Bangkok', 'Bangkok, Thailand', 'Thailand', 'Asia', 13.7563, 100.5018, 10539000, 58.82, 'A sensory feast of ornate temples, bustling street markets, and legendary cuisine, Bangkok offers incredibly affordable living and a thriving digital nomad community.', 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=800&q=80'),
  ('seoul', 'Seoul', 'Seoul, South Korea', 'South Korea', 'Asia', 37.5665, 126.978, 9776000, 67.65, 'A hyper-connected metropolis at the forefront of technology and pop culture, Seoul offers blazing-fast internet, rich history, and an electrifying urban energy.', 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=800&q=80'),
  ('taipei', 'Taipei', 'Taipei, Taiwan', 'Taiwan', 'Asia', 25.033, 121.5654, 2646204, 67.06, 'A friendly and affordable Asian capital, Taipei delights with incredible night markets, excellent public transit, and a thriving tech manufacturing ecosystem.', 'https://images.unsplash.com/photo-1470004914212-05527e49370b?auto=format&fit=crop&w=800&q=80'),
  ('hong-kong', 'Hong Kong', 'Hong Kong, China', 'China', 'Asia', 22.3193, 114.1694, 7482500, 62.94, 'A dazzling vertical city where East meets West, Hong Kong offers a world-class financial center, incredible cuisine, and dramatic harbor views.', 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?auto=format&fit=crop&w=800&q=80'),
  ('melbourne', 'Melbourne', 'Melbourne, Australia', 'Australia', 'Oceania', -37.8136, 144.9631, 5078193, 66.47, 'Australia''s cultural capital, Melbourne is famous for its coffee culture, street art, live music scene, and passion for Australian Rules football.', 'https://images.unsplash.com/photo-1514395462725-fb4566210144?auto=format&fit=crop&w=800&q=80'),
  ('sydney', 'Sydney', 'Sydney, Australia', 'Australia', 'Oceania', -33.8688, 151.2093, 5312163, 64.71, 'Home to the iconic Opera House and Harbour Bridge, Sydney offers stunning beaches, a strong economy, and an enviable outdoor lifestyle.', 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800&q=80'),
  ('auckland', 'Auckland', 'Auckland, New Zealand', 'New Zealand', 'Oceania', -36.8485, 174.7633, 1657200, 63.53, 'The City of Sails sits between two harbors surrounded by volcanic cones, offering exceptional outdoor recreation and a relaxed Kiwi lifestyle.', 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=800&q=80'),
  ('buenos-aires', 'Buenos Aires', 'Buenos Aires, Argentina', 'Argentina', 'South America', -34.6037, -58.3816, 3075646, 60.59, 'The Paris of South America enchants with passionate tango, world-class steak, vibrant street art, and an incredibly affordable cosmopolitan lifestyle.', 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=800&q=80'),
  ('medellin', 'Medellin', 'Medellin, Colombia', 'Colombia', 'South America', 6.2476, -75.5658, 2569007, 57.65, 'Once notorious, Medellin has reinvented itself as a city of innovation with eternal spring weather, affordable living, and a booming digital nomad community.', 'https://images.unsplash.com/photo-1583997052103-b4a1cb974ce5?auto=format&fit=crop&w=800&q=80'),
  ('sao-paulo', 'Sao Paulo', 'Sao Paulo, Brazil', 'Brazil', 'South America', -23.5505, -46.6333, 12325232, 55.88, 'South America''s largest city is an economic powerhouse with incredible culinary diversity, a thriving arts scene, and a pulsating nightlife.', 'https://images.unsplash.com/photo-1543059080-0b36deb42620?auto=format&fit=crop&w=800&q=80'),
  ('santiago', 'Santiago', 'Santiago, Chile', 'Chile', 'South America', -33.4489, -70.6693, 6160000, 60.59, 'Framed by the Andes mountains, Santiago offers South America''s most stable economy alongside excellent wine regions and ski resorts within easy reach.', 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80'),
  ('bogota', 'Bogota', 'Bogota, Colombia', 'Colombia', 'South America', 4.711, -74.0721, 7181469, 54.71, 'Colombia''s high-altitude capital is rapidly modernizing, offering affordable living, a growing tech startup scene, and rich cultural heritage.', 'https://images.unsplash.com/photo-1568632234157-ce7aecd03d0d?auto=format&fit=crop&w=800&q=80'),
  ('dubai', 'Dubai', 'Dubai, United Arab Emirates', 'United Arab Emirates', 'Asia', 25.2048, 55.2708, 3331420, 62.94, 'A futuristic desert metropolis, Dubai offers tax-free income, ultra-modern infrastructure, and a global business hub connecting East and West.', 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80'),
  ('tel-aviv', 'Tel Aviv', 'Tel Aviv, Israel', 'Israel', 'Asia', 32.0853, 34.7818, 451523, 62.94, 'The startup nation''s beating heart, Tel Aviv combines Mediterranean beach culture with an incredibly dense tech ecosystem and vibrant nightlife.', 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80'),
  ('cape-town', 'Cape Town', 'Cape Town, South Africa', 'South Africa', 'Africa', -33.9249, 18.4241, 4618000, 56.47, 'Nestled between Table Mountain and the Atlantic Ocean, Cape Town offers breathtaking natural beauty, excellent wine regions, and a vibrant creative scene.', 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=800&q=80'),
  ('nairobi', 'Nairobi', 'Nairobi, Kenya', 'Kenya', 'Africa', -1.2921, 36.8219, 4397073, 51.76, 'East Africa''s largest city and tech hub, Nairobi is a gateway to incredible wildlife safaris with a rapidly growing innovation ecosystem.', 'https://images.unsplash.com/photo-1611348524140-53c9a25263d6?auto=format&fit=crop&w=800&q=80'),
  ('helsinki', 'Helsinki', 'Helsinki, Finland', 'Finland', 'Europe', 60.1699, 24.9384, 656229, 67.06, 'A design-forward Nordic capital, Helsinki offers world-leading education, universal healthcare, excellent saunas, and a strong sense of social equality.', 'https://images.unsplash.com/photo-1538332576228-eb5b4c4de6f5?auto=format&fit=crop&w=800&q=80'),
  ('osaka', 'Osaka', 'Osaka, Japan', 'Japan', 'Asia', 34.6937, 135.5023, 2753862, 67.06, 'Japan''s kitchen and comedy capital, Osaka delights with its street food culture, friendly locals, historic castles, and excellent transit connections.', 'https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=800&q=80'),
  ('kuala-lumpur', 'Kuala Lumpur', 'Kuala Lumpur, Malaysia', 'Malaysia', 'Asia', 3.139, 101.6869, 1982112, 60.59, 'A multicultural Southeast Asian metropolis, Kuala Lumpur offers incredibly affordable living, iconic Petronas Towers, and a delicious fusion food scene.', 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=800&q=80'),
  ('warsaw', 'Warsaw', 'Warsaw, Poland', 'Poland', 'Europe', 52.2297, 21.0122, 1790658, 62.35, 'Rebuilt from wartime devastation, Warsaw is now a dynamic European capital with a booming economy, growing tech scene, and a fascinating blend of old and new.', 'https://images.unsplash.com/photo-1519197924294-4ba991a11128?auto=format&fit=crop&w=800&q=80'),
  ('reykjavik', 'Reykjavik', 'Reykjavik, Iceland', 'Iceland', 'Europe', 64.1466, -21.9426, 131136, 62.94, 'The world''s northernmost capital offers otherworldly volcanic landscapes, geothermal hot springs, the Northern Lights, and an extraordinarily safe society.', 'https://images.unsplash.com/photo-1504829857797-ddff29c09e32?auto=format&fit=crop&w=800&q=80'),
  ('edinburgh', 'Edinburgh', 'Edinburgh, Scotland, United Kingdom', 'United Kingdom', 'Europe', 55.9533, -3.1883, 524930, 64.12, 'Scotland''s historic capital hosts the world''s largest arts festival and offers stunning medieval architecture, excellent universities, and a thriving cultural scene.', 'https://images.unsplash.com/photo-1551009175-15bdf9dcb580?auto=format&fit=crop&w=800&q=80'),
  ('bali', 'Bali', 'Bali (Denpasar), Indonesia', 'Indonesia', 'Asia', -8.3405, 115.092, 4225384, 58.24, 'A tropical paradise for digital nomads, Bali offers stunning rice terraces, Hindu temple culture, world-class surfing, and an incredibly affordable lifestyle.', 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80');

-- City Scores
INSERT INTO city_scores (city_id, category, score) VALUES
  ('san-francisco', 'Housing', 2.0),
  ('san-francisco', 'Cost of Living', 2.5),
  ('san-francisco', 'Startups', 9.5),
  ('san-francisco', 'Venture Capital', 9.0),
  ('san-francisco', 'Travel Connectivity', 7.0),
  ('san-francisco', 'Commute', 4.5),
  ('san-francisco', 'Business Freedom', 8.0),
  ('san-francisco', 'Safety', 5.0),
  ('san-francisco', 'Healthcare', 7.5),
  ('san-francisco', 'Education', 8.0),
  ('san-francisco', 'Environmental Quality', 6.0),
  ('san-francisco', 'Economy', 8.5),
  ('san-francisco', 'Taxation', 4.0),
  ('san-francisco', 'Internet Access', 8.5),
  ('san-francisco', 'Leisure & Culture', 8.0),
  ('san-francisco', 'Tolerance', 8.5),
  ('san-francisco', 'Outdoors', 7.0),
  ('new-york', 'Housing', 1.5),
  ('new-york', 'Cost of Living', 1.5),
  ('new-york', 'Startups', 8.5),
  ('new-york', 'Venture Capital', 8.5),
  ('new-york', 'Travel Connectivity', 9.5),
  ('new-york', 'Commute', 6.5),
  ('new-york', 'Business Freedom', 8.0),
  ('new-york', 'Safety', 5.5),
  ('new-york', 'Healthcare', 8.0),
  ('new-york', 'Education', 8.5),
  ('new-york', 'Environmental Quality', 4.5),
  ('new-york', 'Economy', 9.0),
  ('new-york', 'Taxation', 3.5),
  ('new-york', 'Internet Access', 8.5),
  ('new-york', 'Leisure & Culture', 9.5),
  ('new-york', 'Tolerance', 8.5),
  ('new-york', 'Outdoors', 3.5),
  ('austin', 'Housing', 4.0),
  ('austin', 'Cost of Living', 5.5),
  ('austin', 'Startups', 7.5),
  ('austin', 'Venture Capital', 6.5),
  ('austin', 'Travel Connectivity', 6.0),
  ('austin', 'Commute', 5.0),
  ('austin', 'Business Freedom', 8.0),
  ('austin', 'Safety', 5.5),
  ('austin', 'Healthcare', 7.0),
  ('austin', 'Education', 7.0),
  ('austin', 'Environmental Quality', 5.5),
  ('austin', 'Economy', 7.5),
  ('austin', 'Taxation', 7.5),
  ('austin', 'Internet Access', 8.0),
  ('austin', 'Leisure & Culture', 7.0),
  ('austin', 'Tolerance', 7.0),
  ('austin', 'Outdoors', 5.5),
  ('seattle', 'Housing', 3.0),
  ('seattle', 'Cost of Living', 3.5),
  ('seattle', 'Startups', 8.0),
  ('seattle', 'Venture Capital', 7.5),
  ('seattle', 'Travel Connectivity', 6.5),
  ('seattle', 'Commute', 5.0),
  ('seattle', 'Business Freedom', 8.0),
  ('seattle', 'Safety', 5.5),
  ('seattle', 'Healthcare', 7.5),
  ('seattle', 'Education', 7.5),
  ('seattle', 'Environmental Quality', 7.0),
  ('seattle', 'Economy', 8.0),
  ('seattle', 'Taxation', 7.0),
  ('seattle', 'Internet Access', 8.5),
  ('seattle', 'Leisure & Culture', 7.0),
  ('seattle', 'Tolerance', 8.0),
  ('seattle', 'Outdoors', 7.5),
  ('portland', 'Housing', 4.0),
  ('portland', 'Cost of Living', 5.0),
  ('portland', 'Startups', 6.0),
  ('portland', 'Venture Capital', 4.5),
  ('portland', 'Travel Connectivity', 5.5),
  ('portland', 'Commute', 6.5),
  ('portland', 'Business Freedom', 7.5),
  ('portland', 'Safety', 5.0),
  ('portland', 'Healthcare', 7.0),
  ('portland', 'Education', 7.0),
  ('portland', 'Environmental Quality', 8.0),
  ('portland', 'Economy', 6.5),
  ('portland', 'Taxation', 5.0),
  ('portland', 'Internet Access', 8.0),
  ('portland', 'Leisure & Culture', 8.0),
  ('portland', 'Tolerance', 8.5),
  ('portland', 'Outdoors', 8.0),
  ('denver', 'Housing', 3.5),
  ('denver', 'Cost of Living', 4.5),
  ('denver', 'Startups', 6.5),
  ('denver', 'Venture Capital', 5.5),
  ('denver', 'Travel Connectivity', 7.0),
  ('denver', 'Commute', 5.5),
  ('denver', 'Business Freedom', 7.5),
  ('denver', 'Safety', 5.5),
  ('denver', 'Healthcare', 7.0),
  ('denver', 'Education', 7.0),
  ('denver', 'Environmental Quality', 6.5),
  ('denver', 'Economy', 7.0),
  ('denver', 'Taxation', 6.0),
  ('denver', 'Internet Access', 7.5),
  ('denver', 'Leisure & Culture', 7.0),
  ('denver', 'Tolerance', 7.5),
  ('denver', 'Outdoors', 9.0),
  ('miami', 'Housing', 3.0),
  ('miami', 'Cost of Living', 4.0),
  ('miami', 'Startups', 6.0),
  ('miami', 'Venture Capital', 5.0),
  ('miami', 'Travel Connectivity', 7.5),
  ('miami', 'Commute', 4.0),
  ('miami', 'Business Freedom', 7.5),
  ('miami', 'Safety', 4.5),
  ('miami', 'Healthcare', 6.5),
  ('miami', 'Education', 5.5),
  ('miami', 'Environmental Quality', 5.5),
  ('miami', 'Economy', 6.5),
  ('miami', 'Taxation', 8.0),
  ('miami', 'Internet Access', 7.5),
  ('miami', 'Leisure & Culture', 7.5),
  ('miami', 'Tolerance', 7.0),
  ('miami', 'Outdoors', 8.0),
  ('nashville', 'Housing', 5.0),
  ('nashville', 'Cost of Living', 6.0),
  ('nashville', 'Startups', 4.5),
  ('nashville', 'Venture Capital', 3.5),
  ('nashville', 'Travel Connectivity', 5.5),
  ('nashville', 'Commute', 5.0),
  ('nashville', 'Business Freedom', 7.5),
  ('nashville', 'Safety', 5.0),
  ('nashville', 'Healthcare', 7.5),
  ('nashville', 'Education', 6.0),
  ('nashville', 'Environmental Quality', 5.5),
  ('nashville', 'Economy', 7.0),
  ('nashville', 'Taxation', 7.5),
  ('nashville', 'Internet Access', 7.0),
  ('nashville', 'Leisure & Culture', 7.5),
  ('nashville', 'Tolerance', 5.5),
  ('nashville', 'Outdoors', 5.5),
  ('charleston', 'Housing', 4.5),
  ('charleston', 'Cost of Living', 6.0),
  ('charleston', 'Startups', 3.5),
  ('charleston', 'Venture Capital', 2.0),
  ('charleston', 'Travel Connectivity', 4.0),
  ('charleston', 'Commute', 5.5),
  ('charleston', 'Business Freedom', 7.0),
  ('charleston', 'Safety', 5.5),
  ('charleston', 'Healthcare', 6.5),
  ('charleston', 'Education', 6.0),
  ('charleston', 'Environmental Quality', 6.5),
  ('charleston', 'Economy', 5.5),
  ('charleston', 'Taxation', 6.5),
  ('charleston', 'Internet Access', 6.5),
  ('charleston', 'Leisure & Culture', 8.0),
  ('charleston', 'Tolerance', 5.5),
  ('charleston', 'Outdoors', 7.5),
  ('chicago', 'Housing', 5.0),
  ('chicago', 'Cost of Living', 5.0),
  ('chicago', 'Startups', 7.0),
  ('chicago', 'Venture Capital', 6.5),
  ('chicago', 'Travel Connectivity', 8.5),
  ('chicago', 'Commute', 7.0),
  ('chicago', 'Business Freedom', 7.5),
  ('chicago', 'Safety', 4.5),
  ('chicago', 'Healthcare', 7.5),
  ('chicago', 'Education', 7.5),
  ('chicago', 'Environmental Quality', 5.0),
  ('chicago', 'Economy', 8.0),
  ('chicago', 'Taxation', 4.5),
  ('chicago', 'Internet Access', 8.0),
  ('chicago', 'Leisure & Culture', 8.5),
  ('chicago', 'Tolerance', 7.5),
  ('chicago', 'Outdoors', 3.5),
  ('los-angeles', 'Housing', 2.0),
  ('los-angeles', 'Cost of Living', 2.5),
  ('los-angeles', 'Startups', 7.5),
  ('los-angeles', 'Venture Capital', 7.0),
  ('los-angeles', 'Travel Connectivity', 8.0),
  ('los-angeles', 'Commute', 3.0),
  ('los-angeles', 'Business Freedom', 7.5),
  ('los-angeles', 'Safety', 4.5),
  ('los-angeles', 'Healthcare', 7.0),
  ('los-angeles', 'Education', 7.0),
  ('los-angeles', 'Environmental Quality', 4.0),
  ('los-angeles', 'Economy', 7.5),
  ('los-angeles', 'Taxation', 3.5),
  ('los-angeles', 'Internet Access', 8.0),
  ('los-angeles', 'Leisure & Culture', 9.0),
  ('los-angeles', 'Tolerance', 8.0),
  ('los-angeles', 'Outdoors', 7.5),
  ('boston', 'Housing', 2.0),
  ('boston', 'Cost of Living', 2.5),
  ('boston', 'Startups', 8.0),
  ('boston', 'Venture Capital', 7.5),
  ('boston', 'Travel Connectivity', 7.5),
  ('boston', 'Commute', 6.5),
  ('boston', 'Business Freedom', 8.0),
  ('boston', 'Safety', 6.0),
  ('boston', 'Healthcare', 9.0),
  ('boston', 'Education', 9.0),
  ('boston', 'Environmental Quality', 6.0),
  ('boston', 'Economy', 8.0),
  ('boston', 'Taxation', 4.0),
  ('boston', 'Internet Access', 8.5),
  ('boston', 'Leisure & Culture', 8.0),
  ('boston', 'Tolerance', 8.0),
  ('boston', 'Outdoors', 4.5),
  ('toronto', 'Housing', 3.0),
  ('toronto', 'Cost of Living', 4.0),
  ('toronto', 'Startups', 7.0),
  ('toronto', 'Venture Capital', 6.0),
  ('toronto', 'Travel Connectivity', 7.5),
  ('toronto', 'Commute', 6.0),
  ('toronto', 'Business Freedom', 8.0),
  ('toronto', 'Safety', 7.0),
  ('toronto', 'Healthcare', 8.0),
  ('toronto', 'Education', 7.5),
  ('toronto', 'Environmental Quality', 6.5),
  ('toronto', 'Economy', 7.5),
  ('toronto', 'Taxation', 4.5),
  ('toronto', 'Internet Access', 8.0),
  ('toronto', 'Leisure & Culture', 7.5),
  ('toronto', 'Tolerance', 8.5),
  ('toronto', 'Outdoors', 5.0),
  ('vancouver', 'Housing', 1.5),
  ('vancouver', 'Cost of Living', 3.0),
  ('vancouver', 'Startups', 6.0),
  ('vancouver', 'Venture Capital', 4.5),
  ('vancouver', 'Travel Connectivity', 6.0),
  ('vancouver', 'Commute', 6.0),
  ('vancouver', 'Business Freedom', 7.5),
  ('vancouver', 'Safety', 7.0),
  ('vancouver', 'Healthcare', 8.0),
  ('vancouver', 'Education', 7.0),
  ('vancouver', 'Environmental Quality', 8.5),
  ('vancouver', 'Economy', 6.5),
  ('vancouver', 'Taxation', 4.0),
  ('vancouver', 'Internet Access', 7.5),
  ('vancouver', 'Leisure & Culture', 7.0),
  ('vancouver', 'Tolerance', 9.0),
  ('vancouver', 'Outdoors', 9.0),
  ('montreal', 'Housing', 6.0),
  ('montreal', 'Cost of Living', 6.5),
  ('montreal', 'Startups', 6.0),
  ('montreal', 'Venture Capital', 4.5),
  ('montreal', 'Travel Connectivity', 6.5),
  ('montreal', 'Commute', 6.5),
  ('montreal', 'Business Freedom', 7.5),
  ('montreal', 'Safety', 7.0),
  ('montreal', 'Healthcare', 8.0),
  ('montreal', 'Education', 7.5),
  ('montreal', 'Environmental Quality', 6.0),
  ('montreal', 'Economy', 6.5),
  ('montreal', 'Taxation', 3.5),
  ('montreal', 'Internet Access', 7.5),
  ('montreal', 'Leisure & Culture', 9.0),
  ('montreal', 'Tolerance', 8.0),
  ('montreal', 'Outdoors', 5.5),
  ('mexico-city', 'Housing', 8.0),
  ('mexico-city', 'Cost of Living', 8.0),
  ('mexico-city', 'Startups', 5.5),
  ('mexico-city', 'Venture Capital', 4.0),
  ('mexico-city', 'Travel Connectivity', 7.0),
  ('mexico-city', 'Commute', 3.5),
  ('mexico-city', 'Business Freedom', 5.5),
  ('mexico-city', 'Safety', 4.0),
  ('mexico-city', 'Healthcare', 5.5),
  ('mexico-city', 'Education', 5.5),
  ('mexico-city', 'Environmental Quality', 3.0),
  ('mexico-city', 'Economy', 5.5),
  ('mexico-city', 'Taxation', 5.5),
  ('mexico-city', 'Internet Access', 6.0),
  ('mexico-city', 'Leisure & Culture', 9.0),
  ('mexico-city', 'Tolerance', 6.5),
  ('mexico-city', 'Outdoors', 4.5),
  ('lisbon', 'Housing', 5.5),
  ('lisbon', 'Cost of Living', 7.0),
  ('lisbon', 'Startups', 7.0),
  ('lisbon', 'Venture Capital', 5.0),
  ('lisbon', 'Travel Connectivity', 6.5),
  ('lisbon', 'Commute', 6.0),
  ('lisbon', 'Business Freedom', 7.0),
  ('lisbon', 'Safety', 8.0),
  ('lisbon', 'Healthcare', 6.5),
  ('lisbon', 'Education', 6.0),
  ('lisbon', 'Environmental Quality', 7.0),
  ('lisbon', 'Economy', 5.5),
  ('lisbon', 'Taxation', 5.5),
  ('lisbon', 'Internet Access', 7.0),
  ('lisbon', 'Leisure & Culture', 8.0),
  ('lisbon', 'Tolerance', 7.5),
  ('lisbon', 'Outdoors', 8.0),
  ('london', 'Housing', 1.5),
  ('london', 'Cost of Living', 1.5),
  ('london', 'Startups', 8.5),
  ('london', 'Venture Capital', 8.0),
  ('london', 'Travel Connectivity', 10.0),
  ('london', 'Commute', 7.0),
  ('london', 'Business Freedom', 8.5),
  ('london', 'Safety', 6.0),
  ('london', 'Healthcare', 7.5),
  ('london', 'Education', 8.5),
  ('london', 'Environmental Quality', 5.0),
  ('london', 'Economy', 9.0),
  ('london', 'Taxation', 4.0),
  ('london', 'Internet Access', 8.0),
  ('london', 'Leisure & Culture', 9.5),
  ('london', 'Tolerance', 8.5),
  ('london', 'Outdoors', 3.0),
  ('berlin', 'Housing', 6.0),
  ('berlin', 'Cost of Living', 7.0),
  ('berlin', 'Startups', 8.0),
  ('berlin', 'Venture Capital', 7.0),
  ('berlin', 'Travel Connectivity', 8.5),
  ('berlin', 'Commute', 8.0),
  ('berlin', 'Business Freedom', 7.5),
  ('berlin', 'Safety', 7.0),
  ('berlin', 'Healthcare', 8.0),
  ('berlin', 'Education', 7.5),
  ('berlin', 'Environmental Quality', 6.5),
  ('berlin', 'Economy', 7.0),
  ('berlin', 'Taxation', 4.5),
  ('berlin', 'Internet Access', 7.0),
  ('berlin', 'Leisure & Culture', 9.0),
  ('berlin', 'Tolerance', 9.0),
  ('berlin', 'Outdoors', 5.5),
  ('barcelona', 'Housing', 4.0),
  ('barcelona', 'Cost of Living', 5.0),
  ('barcelona', 'Startups', 6.5),
  ('barcelona', 'Venture Capital', 4.5),
  ('barcelona', 'Travel Connectivity', 8.0),
  ('barcelona', 'Commute', 7.5),
  ('barcelona', 'Business Freedom', 6.5),
  ('barcelona', 'Safety', 6.5),
  ('barcelona', 'Healthcare', 8.0),
  ('barcelona', 'Education', 7.0),
  ('barcelona', 'Environmental Quality', 6.5),
  ('barcelona', 'Economy', 6.0),
  ('barcelona', 'Taxation', 4.5),
  ('barcelona', 'Internet Access', 7.5),
  ('barcelona', 'Leisure & Culture', 9.0),
  ('barcelona', 'Tolerance', 8.0),
  ('barcelona', 'Outdoors', 8.0),
  ('amsterdam', 'Housing', 3.0),
  ('amsterdam', 'Cost of Living', 4.0),
  ('amsterdam', 'Startups', 7.0),
  ('amsterdam', 'Venture Capital', 6.0),
  ('amsterdam', 'Travel Connectivity', 9.0),
  ('amsterdam', 'Commute', 9.0),
  ('amsterdam', 'Business Freedom', 8.0),
  ('amsterdam', 'Safety', 7.5),
  ('amsterdam', 'Healthcare', 8.5),
  ('amsterdam', 'Education', 7.5),
  ('amsterdam', 'Environmental Quality', 6.5),
  ('amsterdam', 'Economy', 7.5),
  ('amsterdam', 'Taxation', 4.5),
  ('amsterdam', 'Internet Access', 8.5),
  ('amsterdam', 'Leisure & Culture', 8.5),
  ('amsterdam', 'Tolerance', 10.0),
  ('amsterdam', 'Outdoors', 5.5),
  ('paris', 'Housing', 2.0),
  ('paris', 'Cost of Living', 2.0),
  ('paris', 'Startups', 7.5),
  ('paris', 'Venture Capital', 6.5),
  ('paris', 'Travel Connectivity', 9.0),
  ('paris', 'Commute', 7.5),
  ('paris', 'Business Freedom', 6.5),
  ('paris', 'Safety', 6.0),
  ('paris', 'Healthcare', 8.5),
  ('paris', 'Education', 8.0),
  ('paris', 'Environmental Quality', 5.5),
  ('paris', 'Economy', 8.5),
  ('paris', 'Taxation', 3.0),
  ('paris', 'Internet Access', 7.5),
  ('paris', 'Leisure & Culture', 10.0),
  ('paris', 'Tolerance', 7.5),
  ('paris', 'Outdoors', 4.5),
  ('prague', 'Housing', 6.0),
  ('prague', 'Cost of Living', 8.0),
  ('prague', 'Startups', 6.0),
  ('prague', 'Venture Capital', 4.0),
  ('prague', 'Travel Connectivity', 7.0),
  ('prague', 'Commute', 7.5),
  ('prague', 'Business Freedom', 7.0),
  ('prague', 'Safety', 8.0),
  ('prague', 'Healthcare', 6.5),
  ('prague', 'Education', 6.5),
  ('prague', 'Environmental Quality', 5.5),
  ('prague', 'Economy', 6.0),
  ('prague', 'Taxation', 5.5),
  ('prague', 'Internet Access', 7.0),
  ('prague', 'Leisure & Culture', 7.5),
  ('prague', 'Tolerance', 6.0),
  ('prague', 'Outdoors', 7.0),
  ('copenhagen', 'Housing', 3.5),
  ('copenhagen', 'Cost of Living', 2.0),
  ('copenhagen', 'Startups', 7.0),
  ('copenhagen', 'Venture Capital', 5.5),
  ('copenhagen', 'Travel Connectivity', 7.5),
  ('copenhagen', 'Commute', 9.0),
  ('copenhagen', 'Business Freedom', 8.5),
  ('copenhagen', 'Safety', 8.5),
  ('copenhagen', 'Healthcare', 9.0),
  ('copenhagen', 'Education', 8.0),
  ('copenhagen', 'Environmental Quality', 8.0),
  ('copenhagen', 'Economy', 7.0),
  ('copenhagen', 'Taxation', 3.0),
  ('copenhagen', 'Internet Access', 8.5),
  ('copenhagen', 'Leisure & Culture', 7.5),
  ('copenhagen', 'Tolerance', 9.0),
  ('copenhagen', 'Outdoors', 4.5),
  ('stockholm', 'Housing', 3.5),
  ('stockholm', 'Cost of Living', 3.0),
  ('stockholm', 'Startups', 8.0),
  ('stockholm', 'Venture Capital', 7.0),
  ('stockholm', 'Travel Connectivity', 7.0),
  ('stockholm', 'Commute', 7.5),
  ('stockholm', 'Business Freedom', 8.0),
  ('stockholm', 'Safety', 8.0),
  ('stockholm', 'Healthcare', 9.0),
  ('stockholm', 'Education', 8.0),
  ('stockholm', 'Environmental Quality', 8.0),
  ('stockholm', 'Economy', 7.5),
  ('stockholm', 'Taxation', 3.0),
  ('stockholm', 'Internet Access', 8.5),
  ('stockholm', 'Leisure & Culture', 7.5),
  ('stockholm', 'Tolerance', 9.0),
  ('stockholm', 'Outdoors', 5.5),
  ('dublin', 'Housing', 2.5),
  ('dublin', 'Cost of Living', 4.0),
  ('dublin', 'Startups', 7.0),
  ('dublin', 'Venture Capital', 5.5),
  ('dublin', 'Travel Connectivity', 7.0),
  ('dublin', 'Commute', 5.5),
  ('dublin', 'Business Freedom', 8.5),
  ('dublin', 'Safety', 7.5),
  ('dublin', 'Healthcare', 6.5),
  ('dublin', 'Education', 7.5),
  ('dublin', 'Environmental Quality', 7.0),
  ('dublin', 'Economy', 7.5),
  ('dublin', 'Taxation', 5.0),
  ('dublin', 'Internet Access', 7.5),
  ('dublin', 'Leisure & Culture', 7.0),
  ('dublin', 'Tolerance', 8.0),
  ('dublin', 'Outdoors', 5.5),
  ('tallinn', 'Housing', 7.0),
  ('tallinn', 'Cost of Living', 7.0),
  ('tallinn', 'Startups', 8.0),
  ('tallinn', 'Venture Capital', 5.5),
  ('tallinn', 'Travel Connectivity', 5.5),
  ('tallinn', 'Commute', 7.0),
  ('tallinn', 'Business Freedom', 9.0),
  ('tallinn', 'Safety', 7.5),
  ('tallinn', 'Healthcare', 6.5),
  ('tallinn', 'Education', 7.0),
  ('tallinn', 'Environmental Quality', 7.0),
  ('tallinn', 'Economy', 6.5),
  ('tallinn', 'Taxation', 7.0),
  ('tallinn', 'Internet Access', 10.0),
  ('tallinn', 'Leisure & Culture', 5.5),
  ('tallinn', 'Tolerance', 6.5),
  ('tallinn', 'Outdoors', 5.5),
  ('zurich', 'Housing', 1.0),
  ('zurich', 'Cost of Living', 1.0),
  ('zurich', 'Startups', 6.5),
  ('zurich', 'Venture Capital', 6.0),
  ('zurich', 'Travel Connectivity', 8.5),
  ('zurich', 'Commute', 8.5),
  ('zurich', 'Business Freedom', 8.5),
  ('zurich', 'Safety', 10.0),
  ('zurich', 'Healthcare', 10.0),
  ('zurich', 'Education', 8.5),
  ('zurich', 'Environmental Quality', 9.0),
  ('zurich', 'Economy', 9.0),
  ('zurich', 'Taxation', 5.0),
  ('zurich', 'Internet Access', 8.5),
  ('zurich', 'Leisure & Culture', 7.0),
  ('zurich', 'Tolerance', 7.5),
  ('zurich', 'Outdoors', 8.0),
  ('vienna', 'Housing', 5.0),
  ('vienna', 'Cost of Living', 5.0),
  ('vienna', 'Startups', 5.5),
  ('vienna', 'Venture Capital', 4.5),
  ('vienna', 'Travel Connectivity', 8.0),
  ('vienna', 'Commute', 8.5),
  ('vienna', 'Business Freedom', 7.5),
  ('vienna', 'Safety', 9.0),
  ('vienna', 'Healthcare', 9.0),
  ('vienna', 'Education', 8.0),
  ('vienna', 'Environmental Quality', 8.0),
  ('vienna', 'Economy', 7.5),
  ('vienna', 'Taxation', 4.0),
  ('vienna', 'Internet Access', 7.5),
  ('vienna', 'Leisure & Culture', 9.0),
  ('vienna', 'Tolerance', 7.5),
  ('vienna', 'Outdoors', 6.5),
  ('munich', 'Housing', 2.5),
  ('munich', 'Cost of Living', 3.5),
  ('munich', 'Startups', 6.5),
  ('munich', 'Venture Capital', 5.5),
  ('munich', 'Travel Connectivity', 8.0),
  ('munich', 'Commute', 8.0),
  ('munich', 'Business Freedom', 7.5),
  ('munich', 'Safety', 8.0),
  ('munich', 'Healthcare', 8.5),
  ('munich', 'Education', 8.0),
  ('munich', 'Environmental Quality', 7.5),
  ('munich', 'Economy', 9.0),
  ('munich', 'Taxation', 4.0),
  ('munich', 'Internet Access', 7.5),
  ('munich', 'Leisure & Culture', 7.5),
  ('munich', 'Tolerance', 7.0),
  ('munich', 'Outdoors', 8.0),
  ('tokyo', 'Housing', 3.5),
  ('tokyo', 'Cost of Living', 4.0),
  ('tokyo', 'Startups', 6.5),
  ('tokyo', 'Venture Capital', 5.5),
  ('tokyo', 'Travel Connectivity', 9.5),
  ('tokyo', 'Commute', 8.5),
  ('tokyo', 'Business Freedom', 7.0),
  ('tokyo', 'Safety', 10.0),
  ('tokyo', 'Healthcare', 8.5),
  ('tokyo', 'Education', 7.5),
  ('tokyo', 'Environmental Quality', 6.5),
  ('tokyo', 'Economy', 8.0),
  ('tokyo', 'Taxation', 5.0),
  ('tokyo', 'Internet Access', 9.0),
  ('tokyo', 'Leisure & Culture', 9.0),
  ('tokyo', 'Tolerance', 5.5),
  ('tokyo', 'Outdoors', 6.0),
  ('singapore', 'Housing', 2.0),
  ('singapore', 'Cost of Living', 2.0),
  ('singapore', 'Startups', 7.5),
  ('singapore', 'Venture Capital', 7.0),
  ('singapore', 'Travel Connectivity', 9.5),
  ('singapore', 'Commute', 8.5),
  ('singapore', 'Business Freedom', 9.5),
  ('singapore', 'Safety', 10.0),
  ('singapore', 'Healthcare', 8.5),
  ('singapore', 'Education', 8.0),
  ('singapore', 'Environmental Quality', 7.0),
  ('singapore', 'Economy', 10.0),
  ('singapore', 'Taxation', 8.0),
  ('singapore', 'Internet Access', 9.5),
  ('singapore', 'Leisure & Culture', 6.5),
  ('singapore', 'Tolerance', 5.0),
  ('singapore', 'Outdoors', 3.0),
  ('bangkok', 'Housing', 8.5),
  ('bangkok', 'Cost of Living', 9.0),
  ('bangkok', 'Startups', 4.5),
  ('bangkok', 'Venture Capital', 3.5),
  ('bangkok', 'Travel Connectivity', 7.5),
  ('bangkok', 'Commute', 3.5),
  ('bangkok', 'Business Freedom', 5.5),
  ('bangkok', 'Safety', 4.0),
  ('bangkok', 'Healthcare', 6.5),
  ('bangkok', 'Education', 4.5),
  ('bangkok', 'Environmental Quality', 3.0),
  ('bangkok', 'Economy', 5.5),
  ('bangkok', 'Taxation', 7.0),
  ('bangkok', 'Internet Access', 7.0),
  ('bangkok', 'Leisure & Culture', 8.0),
  ('bangkok', 'Tolerance', 6.0),
  ('bangkok', 'Outdoors', 4.5),
  ('seoul', 'Housing', 3.5),
  ('seoul', 'Cost of Living', 5.0),
  ('seoul', 'Startups', 7.5),
  ('seoul', 'Venture Capital', 6.5),
  ('seoul', 'Travel Connectivity', 8.5),
  ('seoul', 'Commute', 8.0),
  ('seoul', 'Business Freedom', 7.0),
  ('seoul', 'Safety', 8.0),
  ('seoul', 'Healthcare', 8.0),
  ('seoul', 'Education', 8.0),
  ('seoul', 'Environmental Quality', 5.0),
  ('seoul', 'Economy', 8.5),
  ('seoul', 'Taxation', 6.0),
  ('seoul', 'Internet Access', 10.0),
  ('seoul', 'Leisure & Culture', 8.0),
  ('seoul', 'Tolerance', 5.0),
  ('seoul', 'Outdoors', 5.5),
  ('taipei', 'Housing', 5.0),
  ('taipei', 'Cost of Living', 7.0),
  ('taipei', 'Startups', 6.5),
  ('taipei', 'Venture Capital', 5.0),
  ('taipei', 'Travel Connectivity', 7.0),
  ('taipei', 'Commute', 7.5),
  ('taipei', 'Business Freedom', 7.0),
  ('taipei', 'Safety', 8.0),
  ('taipei', 'Healthcare', 8.0),
  ('taipei', 'Education', 7.0),
  ('taipei', 'Environmental Quality', 5.5),
  ('taipei', 'Economy', 7.0),
  ('taipei', 'Taxation', 6.5),
  ('taipei', 'Internet Access', 9.0),
  ('taipei', 'Leisure & Culture', 7.0),
  ('taipei', 'Tolerance', 7.0),
  ('taipei', 'Outdoors', 6.5),
  ('hong-kong', 'Housing', 1.0),
  ('hong-kong', 'Cost of Living', 2.0),
  ('hong-kong', 'Startups', 6.5),
  ('hong-kong', 'Venture Capital', 6.0),
  ('hong-kong', 'Travel Connectivity', 9.0),
  ('hong-kong', 'Commute', 8.0),
  ('hong-kong', 'Business Freedom', 8.5),
  ('hong-kong', 'Safety', 8.0),
  ('hong-kong', 'Healthcare', 7.5),
  ('hong-kong', 'Education', 7.0),
  ('hong-kong', 'Environmental Quality', 4.0),
  ('hong-kong', 'Economy', 9.0),
  ('hong-kong', 'Taxation', 8.0),
  ('hong-kong', 'Internet Access', 9.0),
  ('hong-kong', 'Leisure & Culture', 7.0),
  ('hong-kong', 'Tolerance', 5.5),
  ('hong-kong', 'Outdoors', 5.0),
  ('melbourne', 'Housing', 3.5),
  ('melbourne', 'Cost of Living', 4.0),
  ('melbourne', 'Startups', 6.0),
  ('melbourne', 'Venture Capital', 5.0),
  ('melbourne', 'Travel Connectivity', 6.5),
  ('melbourne', 'Commute', 6.0),
  ('melbourne', 'Business Freedom', 8.0),
  ('melbourne', 'Safety', 7.5),
  ('melbourne', 'Healthcare', 8.0),
  ('melbourne', 'Education', 8.0),
  ('melbourne', 'Environmental Quality', 7.5),
  ('melbourne', 'Economy', 7.0),
  ('melbourne', 'Taxation', 5.0),
  ('melbourne', 'Internet Access', 7.0),
  ('melbourne', 'Leisure & Culture', 8.0),
  ('melbourne', 'Tolerance', 8.0),
  ('melbourne', 'Outdoors', 8.0),
  ('sydney', 'Housing', 2.0),
  ('sydney', 'Cost of Living', 2.5),
  ('sydney', 'Startups', 6.0),
  ('sydney', 'Venture Capital', 5.0),
  ('sydney', 'Travel Connectivity', 7.0),
  ('sydney', 'Commute', 5.5),
  ('sydney', 'Business Freedom', 8.0),
  ('sydney', 'Safety', 7.5),
  ('sydney', 'Healthcare', 8.0),
  ('sydney', 'Education', 8.0),
  ('sydney', 'Environmental Quality', 7.5),
  ('sydney', 'Economy', 8.0),
  ('sydney', 'Taxation', 5.0),
  ('sydney', 'Internet Access', 7.0),
  ('sydney', 'Leisure & Culture', 7.5),
  ('sydney', 'Tolerance', 8.0),
  ('sydney', 'Outdoors', 9.0),
  ('auckland', 'Housing', 2.5),
  ('auckland', 'Cost of Living', 4.0),
  ('auckland', 'Startups', 5.0),
  ('auckland', 'Venture Capital', 3.5),
  ('auckland', 'Travel Connectivity', 4.5),
  ('auckland', 'Commute', 5.5),
  ('auckland', 'Business Freedom', 8.5),
  ('auckland', 'Safety', 8.0),
  ('auckland', 'Healthcare', 7.5),
  ('auckland', 'Education', 7.0),
  ('auckland', 'Environmental Quality', 8.5),
  ('auckland', 'Economy', 6.5),
  ('auckland', 'Taxation', 5.0),
  ('auckland', 'Internet Access', 7.0),
  ('auckland', 'Leisure & Culture', 6.5),
  ('auckland', 'Tolerance', 8.0),
  ('auckland', 'Outdoors', 9.0),
  ('buenos-aires', 'Housing', 7.5),
  ('buenos-aires', 'Cost of Living', 8.0),
  ('buenos-aires', 'Startups', 5.0),
  ('buenos-aires', 'Venture Capital', 3.0),
  ('buenos-aires', 'Travel Connectivity', 5.5),
  ('buenos-aires', 'Commute', 5.5),
  ('buenos-aires', 'Business Freedom', 4.5),
  ('buenos-aires', 'Safety', 4.0),
  ('buenos-aires', 'Healthcare', 6.5),
  ('buenos-aires', 'Education', 6.5),
  ('buenos-aires', 'Environmental Quality', 5.5),
  ('buenos-aires', 'Economy', 4.0),
  ('buenos-aires', 'Taxation', 3.5),
  ('buenos-aires', 'Internet Access', 6.5),
  ('buenos-aires', 'Leisure & Culture', 9.0),
  ('buenos-aires', 'Tolerance', 7.5),
  ('buenos-aires', 'Outdoors', 5.5),
  ('medellin', 'Housing', 8.0),
  ('medellin', 'Cost of Living', 8.0),
  ('medellin', 'Startups', 4.5),
  ('medellin', 'Venture Capital', 2.5),
  ('medellin', 'Travel Connectivity', 4.0),
  ('medellin', 'Commute', 5.0),
  ('medellin', 'Business Freedom', 5.0),
  ('medellin', 'Safety', 4.5),
  ('medellin', 'Healthcare', 6.0),
  ('medellin', 'Education', 5.0),
  ('medellin', 'Environmental Quality', 6.5),
  ('medellin', 'Economy', 4.5),
  ('medellin', 'Taxation', 5.5),
  ('medellin', 'Internet Access', 6.5),
  ('medellin', 'Leisure & Culture', 6.0),
  ('medellin', 'Tolerance', 6.0),
  ('medellin', 'Outdoors', 8.0),
  ('sao-paulo', 'Housing', 5.0),
  ('sao-paulo', 'Cost of Living', 5.0),
  ('sao-paulo', 'Startups', 6.0),
  ('sao-paulo', 'Venture Capital', 5.0),
  ('sao-paulo', 'Travel Connectivity', 6.5),
  ('sao-paulo', 'Commute', 3.0),
  ('sao-paulo', 'Business Freedom', 4.5),
  ('sao-paulo', 'Safety', 3.0),
  ('sao-paulo', 'Healthcare', 6.0),
  ('sao-paulo', 'Education', 5.5),
  ('sao-paulo', 'Environmental Quality', 4.0),
  ('sao-paulo', 'Economy', 8.0),
  ('sao-paulo', 'Taxation', 3.5),
  ('sao-paulo', 'Internet Access', 6.5),
  ('sao-paulo', 'Leisure & Culture', 7.5),
  ('sao-paulo', 'Tolerance', 7.0),
  ('sao-paulo', 'Outdoors', 4.5),
  ('santiago', 'Housing', 5.5),
  ('santiago', 'Cost of Living', 5.0),
  ('santiago', 'Startups', 5.5),
  ('santiago', 'Venture Capital', 4.0),
  ('santiago', 'Travel Connectivity', 5.0),
  ('santiago', 'Commute', 5.5),
  ('santiago', 'Business Freedom', 7.0),
  ('santiago', 'Safety', 5.5),
  ('santiago', 'Healthcare', 7.0),
  ('santiago', 'Education', 6.5),
  ('santiago', 'Environmental Quality', 5.0),
  ('santiago', 'Economy', 7.0),
  ('santiago', 'Taxation', 6.0),
  ('santiago', 'Internet Access', 7.0),
  ('santiago', 'Leisure & Culture', 6.0),
  ('santiago', 'Tolerance', 5.5),
  ('santiago', 'Outdoors', 7.5),
  ('bogota', 'Housing', 7.0),
  ('bogota', 'Cost of Living', 7.0),
  ('bogota', 'Startups', 5.0),
  ('bogota', 'Venture Capital', 3.0),
  ('bogota', 'Travel Connectivity', 4.5),
  ('bogota', 'Commute', 3.5),
  ('bogota', 'Business Freedom', 5.0),
  ('bogota', 'Safety', 4.0),
  ('bogota', 'Healthcare', 5.5),
  ('bogota', 'Education', 5.0),
  ('bogota', 'Environmental Quality', 4.5),
  ('bogota', 'Economy', 5.0),
  ('bogota', 'Taxation', 5.5),
  ('bogota', 'Internet Access', 6.0),
  ('bogota', 'Leisure & Culture', 6.5),
  ('bogota', 'Tolerance', 5.5),
  ('bogota', 'Outdoors', 5.5),
  ('dubai', 'Housing', 4.0),
  ('dubai', 'Cost of Living', 4.0),
  ('dubai', 'Startups', 6.0),
  ('dubai', 'Venture Capital', 5.0),
  ('dubai', 'Travel Connectivity', 9.5),
  ('dubai', 'Commute', 5.5),
  ('dubai', 'Business Freedom', 7.5),
  ('dubai', 'Safety', 9.0),
  ('dubai', 'Healthcare', 7.0),
  ('dubai', 'Education', 6.0),
  ('dubai', 'Environmental Quality', 4.0),
  ('dubai', 'Economy', 8.5),
  ('dubai', 'Taxation', 10.0),
  ('dubai', 'Internet Access', 7.5),
  ('dubai', 'Leisure & Culture', 5.5),
  ('dubai', 'Tolerance', 3.0),
  ('dubai', 'Outdoors', 3.0),
  ('tel-aviv', 'Housing', 2.0),
  ('tel-aviv', 'Cost of Living', 2.5),
  ('tel-aviv', 'Startups', 9.0),
  ('tel-aviv', 'Venture Capital', 8.0),
  ('tel-aviv', 'Travel Connectivity', 6.0),
  ('tel-aviv', 'Commute', 5.0),
  ('tel-aviv', 'Business Freedom', 7.0),
  ('tel-aviv', 'Safety', 5.0),
  ('tel-aviv', 'Healthcare', 7.5),
  ('tel-aviv', 'Education', 7.5),
  ('tel-aviv', 'Environmental Quality', 5.5),
  ('tel-aviv', 'Economy', 7.5),
  ('tel-aviv', 'Taxation', 4.0),
  ('tel-aviv', 'Internet Access', 8.0),
  ('tel-aviv', 'Leisure & Culture', 8.0),
  ('tel-aviv', 'Tolerance', 7.0),
  ('tel-aviv', 'Outdoors', 7.5),
  ('cape-town', 'Housing', 6.5),
  ('cape-town', 'Cost of Living', 7.0),
  ('cape-town', 'Startups', 4.5),
  ('cape-town', 'Venture Capital', 3.0),
  ('cape-town', 'Travel Connectivity', 4.5),
  ('cape-town', 'Commute', 4.5),
  ('cape-town', 'Business Freedom', 6.0),
  ('cape-town', 'Safety', 3.0),
  ('cape-town', 'Healthcare', 5.0),
  ('cape-town', 'Education', 5.5),
  ('cape-town', 'Environmental Quality', 7.0),
  ('cape-town', 'Economy', 5.5),
  ('cape-town', 'Taxation', 5.0),
  ('cape-town', 'Internet Access', 6.0),
  ('cape-town', 'Leisure & Culture', 7.0),
  ('cape-town', 'Tolerance', 6.0),
  ('cape-town', 'Outdoors', 9.0),
  ('nairobi', 'Housing', 7.5),
  ('nairobi', 'Cost of Living', 8.0),
  ('nairobi', 'Startups', 6.0),
  ('nairobi', 'Venture Capital', 3.5),
  ('nairobi', 'Travel Connectivity', 4.5),
  ('nairobi', 'Commute', 3.0),
  ('nairobi', 'Business Freedom', 5.0),
  ('nairobi', 'Safety', 3.5),
  ('nairobi', 'Healthcare', 3.5),
  ('nairobi', 'Education', 4.0),
  ('nairobi', 'Environmental Quality', 5.0),
  ('nairobi', 'Economy', 5.0),
  ('nairobi', 'Taxation', 5.5),
  ('nairobi', 'Internet Access', 5.5),
  ('nairobi', 'Leisure & Culture', 5.5),
  ('nairobi', 'Tolerance', 4.5),
  ('nairobi', 'Outdoors', 7.5),
  ('helsinki', 'Housing', 4.5),
  ('helsinki', 'Cost of Living', 3.5),
  ('helsinki', 'Startups', 7.0),
  ('helsinki', 'Venture Capital', 5.5),
  ('helsinki', 'Travel Connectivity', 6.5),
  ('helsinki', 'Commute', 8.0),
  ('helsinki', 'Business Freedom', 8.5),
  ('helsinki', 'Safety', 9.0),
  ('helsinki', 'Healthcare', 9.0),
  ('helsinki', 'Education', 9.0),
  ('helsinki', 'Environmental Quality', 8.5),
  ('helsinki', 'Economy', 7.0),
  ('helsinki', 'Taxation', 3.0),
  ('helsinki', 'Internet Access', 8.5),
  ('helsinki', 'Leisure & Culture', 7.0),
  ('helsinki', 'Tolerance', 8.5),
  ('helsinki', 'Outdoors', 4.0),
  ('osaka', 'Housing', 5.5),
  ('osaka', 'Cost of Living', 5.0),
  ('osaka', 'Startups', 5.0),
  ('osaka', 'Venture Capital', 4.0),
  ('osaka', 'Travel Connectivity', 8.0),
  ('osaka', 'Commute', 8.0),
  ('osaka', 'Business Freedom', 7.0),
  ('osaka', 'Safety', 9.0),
  ('osaka', 'Healthcare', 8.5),
  ('osaka', 'Education', 7.0),
  ('osaka', 'Environmental Quality', 6.5),
  ('osaka', 'Economy', 7.0),
  ('osaka', 'Taxation', 5.0),
  ('osaka', 'Internet Access', 8.5),
  ('osaka', 'Leisure & Culture', 8.0),
  ('osaka', 'Tolerance', 5.5),
  ('osaka', 'Outdoors', 6.0),
  ('kuala-lumpur', 'Housing', 8.0),
  ('kuala-lumpur', 'Cost of Living', 9.0),
  ('kuala-lumpur', 'Startups', 4.5),
  ('kuala-lumpur', 'Venture Capital', 3.5),
  ('kuala-lumpur', 'Travel Connectivity', 7.0),
  ('kuala-lumpur', 'Commute', 5.0),
  ('kuala-lumpur', 'Business Freedom', 6.0),
  ('kuala-lumpur', 'Safety', 6.0),
  ('kuala-lumpur', 'Healthcare', 6.5),
  ('kuala-lumpur', 'Education', 5.5),
  ('kuala-lumpur', 'Environmental Quality', 4.5),
  ('kuala-lumpur', 'Economy', 6.5),
  ('kuala-lumpur', 'Taxation', 6.5),
  ('kuala-lumpur', 'Internet Access', 7.5),
  ('kuala-lumpur', 'Leisure & Culture', 6.5),
  ('kuala-lumpur', 'Tolerance', 5.0),
  ('kuala-lumpur', 'Outdoors', 5.5),
  ('warsaw', 'Housing', 6.5),
  ('warsaw', 'Cost of Living', 7.0),
  ('warsaw', 'Startups', 5.5),
  ('warsaw', 'Venture Capital', 4.0),
  ('warsaw', 'Travel Connectivity', 6.5),
  ('warsaw', 'Commute', 6.5),
  ('warsaw', 'Business Freedom', 6.5),
  ('warsaw', 'Safety', 7.5),
  ('warsaw', 'Healthcare', 5.5),
  ('warsaw', 'Education', 6.5),
  ('warsaw', 'Environmental Quality', 5.0),
  ('warsaw', 'Economy', 7.0),
  ('warsaw', 'Taxation', 6.0),
  ('warsaw', 'Internet Access', 7.5),
  ('warsaw', 'Leisure & Culture', 6.5),
  ('warsaw', 'Tolerance', 5.0),
  ('warsaw', 'Outdoors', 5.0),
  ('reykjavik', 'Housing', 3.0),
  ('reykjavik', 'Cost of Living', 2.0),
  ('reykjavik', 'Startups', 4.5),
  ('reykjavik', 'Venture Capital', 2.5),
  ('reykjavik', 'Travel Connectivity', 5.0),
  ('reykjavik', 'Commute', 7.0),
  ('reykjavik', 'Business Freedom', 8.0),
  ('reykjavik', 'Safety', 9.5),
  ('reykjavik', 'Healthcare', 8.5),
  ('reykjavik', 'Education', 7.5),
  ('reykjavik', 'Environmental Quality', 9.5),
  ('reykjavik', 'Economy', 4.5),
  ('reykjavik', 'Taxation', 4.0),
  ('reykjavik', 'Internet Access', 8.0),
  ('reykjavik', 'Leisure & Culture', 6.0),
  ('reykjavik', 'Tolerance', 9.0),
  ('reykjavik', 'Outdoors', 9.5),
  ('edinburgh', 'Housing', 4.0),
  ('edinburgh', 'Cost of Living', 5.0),
  ('edinburgh', 'Startups', 5.5),
  ('edinburgh', 'Venture Capital', 4.0),
  ('edinburgh', 'Travel Connectivity', 6.5),
  ('edinburgh', 'Commute', 7.0),
  ('edinburgh', 'Business Freedom', 8.0),
  ('edinburgh', 'Safety', 7.5),
  ('edinburgh', 'Healthcare', 7.5),
  ('edinburgh', 'Education', 8.0),
  ('edinburgh', 'Environmental Quality', 7.0),
  ('edinburgh', 'Economy', 6.5),
  ('edinburgh', 'Taxation', 4.0),
  ('edinburgh', 'Internet Access', 7.5),
  ('edinburgh', 'Leisure & Culture', 8.0),
  ('edinburgh', 'Tolerance', 8.0),
  ('edinburgh', 'Outdoors', 6.5),
  ('bali', 'Housing', 9.0),
  ('bali', 'Cost of Living', 9.0),
  ('bali', 'Startups', 3.5),
  ('bali', 'Venture Capital', 1.5),
  ('bali', 'Travel Connectivity', 4.5),
  ('bali', 'Commute', 3.5),
  ('bali', 'Business Freedom', 4.5),
  ('bali', 'Safety', 5.5),
  ('bali', 'Healthcare', 4.0),
  ('bali', 'Education', 3.5),
  ('bali', 'Environmental Quality', 7.0),
  ('bali', 'Economy', 4.0),
  ('bali', 'Taxation', 6.5),
  ('bali', 'Internet Access', 5.5),
  ('bali', 'Leisure & Culture', 7.5),
  ('bali', 'Tolerance', 7.0),
  ('bali', 'Outdoors', 9.0);

COMMIT;

-- Stats: 55 cities, 935 score rows